// Auto-generated by Base44
export const appParams = {
  appId: import.meta.env.VITE_APP_ID || '',
  token: import.meta.env.VITE_APP_TOKEN || '',
  functionsVersion: import.meta.env.VITE_FUNCTIONS_VERSION || 'prod',
  appBaseUrl: import.meta.env.VITE_APP_BASE_URL || '',
};
